// <auto-generated />
using BolalarBogchasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BolalarBogchasi.Migrations
{
    [DbContext(typeof(BogchaDB))]
    [Migration("20230803132946_Ishladi")]
    partial class Ishladi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BolalarBogchasi.Models.Bolalar", b =>
                {
                    b.Property<int>("BolaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BolaId"));

                    b.Property<bool>("BolaBogchadami")
                        .HasColumnType("boolean");

                    b.Property<string>("BolaFamiliyasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BolaGuruhi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BolaIsmi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BolaKelganKun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BolaTolovi")
                        .HasColumnType("bigint");

                    b.Property<string>("BolagaBoglanishElektronPochta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BolagaBoglanishTelRaqami")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BolaningManzili")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuruhId")
                        .HasColumnType("integer");

                    b.Property<int>("HaydovchiId")
                        .HasColumnType("integer");

                    b.Property<int>("TarbiyachiId")
                        .HasColumnType("integer");

                    b.HasKey("BolaId");

                    b.HasIndex("GuruhId");

                    b.HasIndex("HaydovchiId");

                    b.HasIndex("TarbiyachiId");

                    b.ToTable("Child");

                    b.HasData(
                        new
                        {
                            BolaId = 1,
                            BolaBogchadami = true,
                            BolaFamiliyasi = "Nobody",
                            BolaGuruhi = "guruh1",
                            BolaIsmi = "Nobody",
                            BolaKelganKun = "01/01/01",
                            BolaTolovi = 270000L,
                            BolagaBoglanishElektronPochta = "Email@gmail.com",
                            BolagaBoglanishTelRaqami = "+000000000000",
                            BolaningManzili = "yunusobod",
                            GuruhId = 1,
                            HaydovchiId = 1,
                            TarbiyachiId = 1
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Guruh", b =>
                {
                    b.Property<int>("GuruhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuruhId"));

                    b.Property<string>("GuruhNomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tarbiyachi_id")
                        .HasColumnType("integer");

                    b.HasKey("GuruhId");

                    b.HasIndex("Tarbiyachi_id");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            GuruhId = 1,
                            GuruhNomi = "guruh1",
                            Tarbiyachi_id = 1
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Haydovchi", b =>
                {
                    b.Property<int>("IshchiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IshchiId"));

                    b.Property<string>("HaydovchiManzili")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IshId")
                        .HasColumnType("integer");

                    b.Property<bool>("IshchiBogchadami")
                        .HasColumnType("boolean");

                    b.Property<string>("IshchiElektronPochta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiFamiliyasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiIsmi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiKelganKun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IshchiMaoshi")
                        .HasColumnType("integer");

                    b.Property<string>("IshchiTelRaqami")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshningNomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IshchiId");

                    b.HasIndex("IshId");

                    b.ToTable("Taxi");

                    b.HasData(
                        new
                        {
                            IshchiId = 1,
                            HaydovchiManzili = "yunusobod",
                            IshId = 1,
                            IshchiBogchadami = true,
                            IshchiElektronPochta = "Haydovchi@gmail.com",
                            IshchiFamiliyasi = "NoOne",
                            IshchiIsmi = "Unknown",
                            IshchiKelganKun = "01/01/01",
                            IshchiMaoshi = 4500000,
                            IshchiTelRaqami = "+000000000000",
                            IshningNomi = "haydovchi"
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Ishlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "haydovchi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "tarbiyachi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "oshpaz"
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Tarbiyachi", b =>
                {
                    b.Property<int>("IshchiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IshchiId"));

                    b.Property<string>("BerilganGuruhNomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IshId")
                        .HasColumnType("integer");

                    b.Property<bool>("IshchiBogchadami")
                        .HasColumnType("boolean");

                    b.Property<string>("IshchiElektronPochta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiFamiliyasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiIsmi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiKelganKun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IshchiMaoshi")
                        .HasColumnType("integer");

                    b.Property<string>("IshchiTelRaqami")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshningNomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IshchiId");

                    b.HasIndex("IshId");

                    b.ToTable("Coach");

                    b.HasData(
                        new
                        {
                            IshchiId = 1,
                            BerilganGuruhNomi = "guruh1",
                            IshId = 2,
                            IshchiBogchadami = true,
                            IshchiElektronPochta = "tarbiyachi@gmail.com",
                            IshchiFamiliyasi = "NoOne",
                            IshchiIsmi = "Unknown",
                            IshchiKelganKun = "01/01/01",
                            IshchiMaoshi = 4500000,
                            IshchiTelRaqami = "+2222222222222",
                            IshningNomi = "tarbiyachi"
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.oshpaz", b =>
                {
                    b.Property<int>("IshchiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IshchiId"));

                    b.Property<int>("IshId")
                        .HasColumnType("integer");

                    b.Property<bool>("IshchiBogchadami")
                        .HasColumnType("boolean");

                    b.Property<string>("IshchiElektronPochta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiFamiliyasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiIsmi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshchiKelganKun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IshchiMaoshi")
                        .HasColumnType("integer");

                    b.Property<string>("IshchiTelRaqami")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IshningNomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IshchiId");

                    b.HasIndex("IshId");

                    b.ToTable("Cook");

                    b.HasData(
                        new
                        {
                            IshchiId = 1,
                            IshId = 3,
                            IshchiBogchadami = true,
                            IshchiElektronPochta = "oshpaz@gmail.com",
                            IshchiFamiliyasi = "NoOne",
                            IshchiIsmi = "Unknown",
                            IshchiKelganKun = "01/01/01",
                            IshchiMaoshi = 4500000,
                            IshchiTelRaqami = "+111111111111",
                            IshningNomi = "oshpaz"
                        });
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Bolalar", b =>
                {
                    b.HasOne("BolalarBogchasi.Models.Guruh", "Guruh")
                        .WithMany("Bola_guruhga")
                        .HasForeignKey("GuruhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolalarBogchasi.Models.Haydovchi", "Haydovchi")
                        .WithMany("Bola_haydovchi")
                        .HasForeignKey("HaydovchiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolalarBogchasi.Models.Tarbiyachi", "Tarbiyachi")
                        .WithMany("Bola_tarbiyachi")
                        .HasForeignKey("TarbiyachiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guruh");

                    b.Navigation("Haydovchi");

                    b.Navigation("Tarbiyachi");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Guruh", b =>
                {
                    b.HasOne("BolalarBogchasi.Models.Tarbiyachi", "Tarbiyachi")
                        .WithMany("guruh_tarbiyachi")
                        .HasForeignKey("Tarbiyachi_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarbiyachi");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Haydovchi", b =>
                {
                    b.HasOne("BolalarBogchasi.Models.Ishlar", "Ishlar")
                        .WithMany("Haydovchi_ish")
                        .HasForeignKey("IshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ishlar");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Tarbiyachi", b =>
                {
                    b.HasOne("BolalarBogchasi.Models.Ishlar", "Ishlar")
                        .WithMany("tarbiyachi_ish")
                        .HasForeignKey("IshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ishlar");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.oshpaz", b =>
                {
                    b.HasOne("BolalarBogchasi.Models.Ishlar", "Ishlar")
                        .WithMany("oshpazlar_ish")
                        .HasForeignKey("IshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ishlar");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Guruh", b =>
                {
                    b.Navigation("Bola_guruhga");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Haydovchi", b =>
                {
                    b.Navigation("Bola_haydovchi");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Ishlar", b =>
                {
                    b.Navigation("Haydovchi_ish");

                    b.Navigation("oshpazlar_ish");

                    b.Navigation("tarbiyachi_ish");
                });

            modelBuilder.Entity("BolalarBogchasi.Models.Tarbiyachi", b =>
                {
                    b.Navigation("Bola_tarbiyachi");

                    b.Navigation("guruh_tarbiyachi");
                });
#pragma warning restore 612, 618
        }
    }
}
